/* 简体中文 */
export function zh_CN(): any {
  return {
    home: '首页',
    action: '操作',
    search: '搜索',
    add: '添加',
    edit: '编辑',
    del: '删除',
    remove: '移除',
    clear: '清空',
    export: '导出',
    copy: '复制',
    mkdir: '新建文件夹',
    rename: '重命名',
    upload: '上传',
    download: '下载',
    prev: '上一步',
    next: '下一步',
    confirm: '确认',
    reset: '重置',
    remark: '备注',
    placeholder: '请输入',
    select: '请选择',
    select_all: '全选',
    select_not: '全不选',
    keyword: '搜索关键字',
    folder: '文件夹',
    file: '文件',
    title: '标题',
    name: '名称',
    info: '基本信息',
    content: '内容',
    size: '大小',
    page: '页码',
    null: '空',
    not: '无',
    logout: '退出登录',
    status: '状态',
    enable: '正常',
    disable: '禁用',
    ctime: '创建时间',
    utime: '更新时间',
    date: '日期',
    network_err: '网络错误',
    del_warn: (num: number)=>{ return '删除 <b>'+num+'</b> 条数据' },
    export_warn: (num: number)=>{ return '导出 <b>'+num+'</b> 条数据' },
    /* Page */
    page_total: (total: number, page: number, num: number)=>{ return '共 <b>'+total+'</b> 条, 第 <b>'+page+'</b>/<b>'+num+'</b> 页' },
    page_limit: '每页',
    /* Login */
    login_uname: '用户名 / 手机号码 / 邮箱',
    login_passwd: '请输入密码',
    login_vcode: '验证码',
    login_refresh: '点击刷新',
    /* Menus */
    menus_placeholder: '搜索菜单',
    menus_recent: '最近访问',
    menus_recommend: '推荐功能',
    /* Uinfo */
    uinfo_title: '用户信息',
    uinfo_img: '更新头像',
    uinfo_type: '类型',
    uinfo_nickname: '昵称',
    uinfo_nickname_placeholder: '用户昵称',
    uinfo_department: '部门',
    uinfo_position: '职位',
    uinfo_name: '姓名',
    uinfo_gender: '性别',
    uinfo_gender_boy: '男',
    uinfo_gender_girl: '女',
    uinfo_birthday: '生日',
    uinfo_signature: '个性签名',
    /* Passwd */
    passwd_title: '修改密码',
    passwd_code_placeholder: '输入验证码',
    passwd_code_get: '获取验证码',
    passwd_code_resend: '重新发送',
    passwd_code_time: (time: number)=>{ return time+'秒后重试' },
    passwd_new: '新密码',
    passwd_confirm: '确认密码',
    passwd_verify_null: '无效帐号',
    passwd_verify_code: '请输入验证码',
    passwd_verify_passwd1: '英文字母开头，6～16位字符',
    passwd_verify_passwd2: '两次密码不一致',
    /* Msg */
    msg_seach: '搜索联系人',
    msg_null: '暂无新消息',
    /* SysFile */
    sys_file_total: (dirNum: number, fileNum: number, size: number)=>{
      return '文件夹: <b>'+(dirNum || 0)+'</b>&nbsp;&nbsp;文件: <b>'+(fileNum || 0)+'</b>&nbsp;&nbsp;大小: <b>'+(size || 0)+'</b>&nbsp;&nbsp;';
    },
    sys_file_rootdir: '根目录',
    sys_file_back: '返回上级',
    sys_file_select_file: '选择文件',
    sys_file_verify_name: '名称2～32字符',
    sys_file_verify_name_exist: '已存在',
    /* SysUser */
    sys_user_total: (num: number)=>{
      return '统计: 共 <b>'+(num || 0)+'</b> 条';
    },
    sys_user_image: '头像',
    sys_user_type: '类型',
    sys_user_role: '角色',
    sys_user_perm: '权限',
    sys_user_uname: '用户名',
    sys_user_passwd: '密码',
    sys_user_base: '基本信息',
    sys_user_nickname: '昵称',
    sys_user_department: '部门',
    sys_user_position: '职位',
    sys_user_name: '姓名',
    sys_user_gender: '性别',
    sys_user_birthday: '生日',
    sys_user_uname_placeholder: '用户名 \\ 手机号码 \\ 邮箱',
    sys_user_passwd_placeholder: '默认密码',
    sys_user_verify_uname: '请输入用户名、手机号码、邮箱',
    sys_user_verify_passwd: '密码为英文字母开头6～16位',
    /* SysRole */
    sys_role_total: (num: number)=>{
      return '统计: 共 <b>'+(num || 0)+'</b> 条';
    },
    sys_role_perm: '权限',
    sys_role_verify_name: '角色名称2～16字符',
    /* SysMenus */
    sys_menus_total: (num: number)=>{
      return '统计: 共 <b>'+(num || 0)+'</b> 条';
    },
    sys_menus_lang: '语言包',
    sys_menus_en_us: 'English',
    sys_menus_zh_cn: '简体中文',
    sys_menus_fid: '所属',
    sys_menus_ico: '图标',
    sys_menus_title: '名称',
    sys_menus_en: '拼音',
    sys_menus_url: '前端地址',
    sys_menus_controller: '后端地址',
    sys_menus_sort: '排序',
    sys_menus_perm: '权限值',
    sys_menus_sort_placeholder: '排序, 如: 0, 1, 2',
    sys_menus_verify_title: '标题必须2～32字符',
    /* WebHtml */
    web_html_total: (num: number)=>{
      return '统计: 共 <b>'+(num || 0)+'</b> 条';
    },
    web_html_type: '类型',
    web_html_title: '标题',
    web_html_name: '名称',
    web_html_verify_title: '标题必须2～32字符',
    web_html_verify_name: '名称必须2～16字符',
  }
}